### ISSUE TITLE
No way to run the tests since jbuilder?

### ISSUE THREAD

**Issue by rixed** [andrenth/ocaml-stdint#32]
I can't find how to run the tests since the build system is jbuilder.
Could this be documented in the README maybe?

Note: I suspect the comparison function is wrong for large int128 and would like to fix it

**Comment by tuncer** [comment]
I'm not the maintainer and can't say if it should be in the README, but have you tried `jbuilder runtest`? Which should be `dune runtest` soon (#35).

**Comment by tuncer** [comment]
I'm not the maintainer and can't say if it should be in the README, but have you tried `jbuilder runtest`? It should change to `dune runtest` soon (#35).

**Comment by rixed** [comment]
Thank you. Will try to go back to this comparison function in a few weeks.

**Comment by rixed** [comment]
Actually `jbuilder runtest` does not do anything it seems, thus the issue I guess.

**Comment by tuncer** [comment]
The project was migrated to jbuilder in 2ed2e978a10b0d8702c6c09e30e44fb35c3e4bd0, and even though the old build files seem to reference testing, I'm not sure where they are and how to integrate them with dune. Are there any tests in the repo? @rgrinberg, thoughts?

**Comment by rgrinberg** [comment]
Yeah that seems like an omission on my part.

**Comment by tuncer** [comment]
@rgrinberg, should we merge #35 and you submit a separate follow-up diff, or do you want to send me a commit on top of #35's branch, which I can add on top? In fact, I think it should be possible for you to send me a pull request in my fork. Otherwise, I'd appreciate hints on what's missing in the dune config.

**Comment by tuncer** [comment]
@rgrinberg, should we merge #35 and you submit a separate follow-up diff, or do you want to send me a commit on top of #35's branch, which I can append? In fact, I think it should be possible for you to send me a pull request in my fork. Otherwise, I'd appreciate hints on what's missing in the dune config.

**Comment by rgrinberg** [comment]
Is it possible to submit #35, and perhaps have you work on the tests? :)

Sorry, I'm a bit swamped at the moment. I could certainly help you out if you have any questions.

**Comment by tuncer** [comment]
I don't mind extending the branch or opening a follow-up pull request, in case you can (quickly) merge #35 first. To that end, how do we integrate the existing tests with Dune? Actually, are there any tests in the repo, and did I fail to uncover them? If there are none, I'm afraid I can't commit to writing them first, since I don't use stdint directly and only did the dune migration to avoid jbuilder in opam-repository.

**Comment by tuncer** [comment]
That said, if there are no tests, I don't mind adding a minimum/trivial test, in order to make `runtest` do something. That way, someone else can implement a test suite with the dune integration already taken care of.

**Comment by tuncer** [comment]
I don't mind extending the branch or opening a follow-up pull request, in case you can (quickly) merge #35 first. To that end, how do we integrate the existing tests with Dune? Actually, are there any tests in the repo, and did I fail to uncover them? If there are none, I'm afraid I can't commit to writing them first, since I don't use stdint directly and only did the dune migration to avoid jbuilder in opam-repository.

That said, if there are no tests, I don't mind adding a minimum/trivial test, in order to make `runtest` do something. That way, someone else can implement a test suite with dune integration already taken care of.

**Comment by rgrinberg** [comment]
I think the spec directory in this project contains a test suite. #35 looks good, but I’m afraid I’m unable to merge it. I’m no a collaborator of this repository.

**Comment by tuncer** [comment]
Right, `spec/*` are meant to be executed with https://github.com/andrenth/ospec. Since OSpec's opam entry says `<4.06.0`, it looks like making the tests work and integrating them with dune is more work than should be bundled into #35.

**Comment by rgrinberg** [comment]
@rixed would you like to revive the tests perahps? it should be sufficient to functorize common.ml and instantiate for the different integer types. Ospec can be dropped in favor of alcotest or ppx_inline_test.

**Comment by rixed** [comment]
@rgrinberg I was just looking at it, but ospec uses camlp4 so that's more work that I'm able to spend right now. I might have more time in a few weeks though.
